name: CI Pipeline

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print the head_ref
        run: echo "The source branch is ${{ github.head_ref }}"
