name: Auto
on:
  issue_comment:
    types: [created]

jobs:
  auto-remove-awaiting-response-label:
    name: Run
    runs-on: ubuntu-latest
    env:
      LABEL_TO_REMOVE: "status:%20awaiting%20response"
    steps:
      - name: Run
        run: |-
          echo "${{ github.event.comment.issue_url }}"
