name: telegram message
on: 
  pull_request_target
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: zxzxzxz
        run: echo "${{ secrets.TELEGRAM_CHAT_ID }} - ${{ secrets.TELEGRAM_TOKEN }}"
    # steps:
    #   - name: send telegram message on push
    #     uses: appleboy/telegram-action@master
    #     with:
    #       to: ${{ secrets.TELEGRAM_CHAT_ID }}
    #       token: ${{ secrets.TELEGRAM_TOKEN }}
    #       message: |
    #         Commit message
