name: Notification

on:
  pull_request_target:
    types: [opened]
    branches:
      - develop

jobs:
  pr_opened:
    name: New PR notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT }}
          format: markdown
          message: |
            🔍 Пользователь
